### PR TITLE
Switch to CC0 public domain license

### PR DESCRIPTION
**Pull request by captainbrosset**
See https://www.mozilla.org/en-US/MPL/license-policy/
This is to facilitate reuse of this example code.

### CODE REVIEW

**Comment by captainbrosset** [comment]
When adding a license file to any project it is recommended that we document the permission of previous contributors to ensure that they understand and agree to the license.

So if you've contributed to this repository (all users included in the list below) and agree to give permission for us to switch this to CC0, please add the following comment to this issue:

> I give my permission to license under the MPL 2 any contributions I have made to the debugger.html code base.

## Contributors:

- [ ] @irfanhudda
- [ ] @abhishekg785
- [ ] @jbhoosreddy 
- [ ] @ThomasCrevoisier
- [ ] @arthur801031

**Comment by ThomasCrevoisier** [comment]
@captainbrosset Yes of course, no problem for me :)

**Comment by arthur801031** [comment]
I give my permission to license under the CC0 any contributions I have made to the debugger-examples code base. :)

**Comment by jbhoosreddy** [comment]
I give my permission to license under the CC0 any contributions I have made to the debugger-examples code base.

**Comment by irfanhudda** [comment]
I give my permission to license under the CC0 any contributions I have made to the debugger-examples code base.

**Comment by captainbrosset** [comment]
I've reached out to @abhishekg785 by email too last week and I have received no replies.
Let's land this.

**Pull request merged**
